Repository Blaybus-Define/BlayBus-Backend, pull requests merged in 2025-01, with the labels that each got.

#3 [Feature] 초기 도메인 설계, 패키지 분리
  blaybus-backend/.gitignore
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/BaseEntity.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/ExperienceRecord.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/ExperienceType.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/Member.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/MemberLevel.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/notification/Notification.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/Post.java
  blaybus-backend/src/main/resources/application.properties
Labels: feature

#4 docs: 시큐리티 권한 변경, 스웨거 세팅
  blaybus-backend/build.gradle
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/Member.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/MemberController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/config/SecurityConfig.java
Labels: documentation

#6 Feature/login 로그인, 회원가입,
  blaybus-backend/build.gradle
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/controller/AuthController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/controller/AuthInterceptor.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/controller/SessionConst.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/LoginRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/LoginResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/LogoutResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/SignupRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/exception/AuthException.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/service/AuthService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/ExperienceRecord.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/MemberController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/MemberLevel.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/controller/MemberController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/JobRole.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/JobRoleType.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/Member.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/MemberLevel.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/exception/MemberException.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/repository/MemberRepository.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/PostController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/config/SecurityConfig.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/config/WebConfig.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/exception/BaseException.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/exception/ErrorCode.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/exception/ErrorResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/exception/GlobalExceptionHandler.java
Labels: feature

#7 fix: 로그인 request 변경
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/LoginRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/SignupRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/service/AuthService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/Member.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/repository/MemberRepository.java
Labels: bug

#8 fix: cors 설정, getter 추가
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/LogoutResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/config/WebConfig.java
Labels: bug, documentation

#12 [ FEATURE] 게시글 등록, 게시글 조회
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/controller/AuthController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/controller/MemberController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/Post.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/PostController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/controller/PostController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/dto/AllPostResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/dto/PostResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/dto/SavePostRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/dto/SavePostResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/entity/Post.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/repository/PostRepository.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/service/PostService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/common/PageResponse.java
Labels: feature

#13 Feature/fcm 게시글 알림
  blaybus-backend/.gitignore
  blaybus-backend/build.gradle
  blaybus-backend/src/main/java/blaybus/blaybus_backend/BlaybusBackendApplication.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/BaseEntity.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/controller/AuthController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/LoginRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/SignupRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/service/AuthService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/controller/MemberController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/Member.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/notification/dto/FcmNotificationDTO.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/notification/entity/Notification.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/notification/entity/NotificationType.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/notification/exception/NotificationException.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/notification/service/NotificationService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/controller/PostController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/dto/SavePostRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/service/PostService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/config/FirebaseConfig.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/config/WebConfig.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/exception/ErrorCode.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/exception/GlobalExceptionHandler.java
Labels: feature

#15 feat: 프로필 캐릭터 수정, 캐릭터 정보 확인
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/controller/MemberController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/dto/InfoResponseDTO.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/dto/UpdatePCharRequestDTO.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/dto/UpdatePCharResponseDTO.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/Member.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/ProfileCharacter.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/service/MemberService.java
Labels: feature

#17 직무별 퀘스트, 리더부여 퀘스트 생성
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/SignupRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/service/AuthService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/JobInfo.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/JobRole.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/JobRoleType.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/Member.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/MemberLevel.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/repository/MemberRepository.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/service/MemberService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/post/dto/SavePostRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/controller/QuestController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/controller/QuestSaveRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/dto/MemberQuestRecordResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/entity/AchievementLevel.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/entity/MemberQuest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/entity/Quest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/repository/MemberQuestRepository.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/repository/QuestRepository.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/service/MemberQuestService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/service/QuestService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/config/WebConfig.java
Labels: feature

#19 퀘스트 완료 처리, 어드민 퀘스트 조회
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/admin/AdminController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/admin/ApproveLeaderQuestRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/admin/ApproveQuestRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/entity/Member.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/repository/MemberRepository.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/controller/QuestController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/controller/QuestSaveRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/dto/MemberQuestRecordResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/entity/AchievementLevel.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/entity/MemberQuest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/exception/QuestException.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/repository/MemberQuestRepository.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/service/QuestService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/global/exception/ErrorCode.java
Labels: feature

#20 refactor: 퀘스트 부여 경험치 응답에 추가
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/dto/MemberQuestRecordResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/entity/Quest.java
Labels: refactor

#30 Feature/admin 어드민 api
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/admin/AdminController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/admin/ApproveLeaderQuestRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/admin/ExperienceQuestRecordResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/admin/ExperienceQuestRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/admin/ExperienceQuestResponse.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/auth/dto/SignupRequest.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/ExperienceRecord.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/ExperienceType.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/controller/ExperienceController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/dto/GainExpResponseDTO.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/entity/GainExperience.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/repository/ExperienceRepository.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/experience/service/ExperienceService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/member/service/MemberService.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/controller/QuestController.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/entity/QuestType.java
  blaybus-backend/src/main/java/blaybus/blaybus_backend/domain/quest/service/QuestService.java
Labels: feature
